[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# hmm?
[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "DARK_EDITION = {0,0,0,1},"
position = "after"
payload = '''
CCC_COLOUR = {0,0,0,1},
'''
match_indent = true

# just doing the same thing
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.C.DARK_EDITION[2] = math.min(self.C.DARK_EDITION[3], self.C.DARK_EDITION[1])"
position = "after"
payload = '''
        self.C.CCC_COLOUR[1] = 0.0+0.1*math.sin(self.TIMERS.REAL*1.3)
        self.C.CCC_COLOUR[3] = 0.8+0.1*(0.0- math.sin(self.TIMERS.REAL*1.3))
        self.C.CCC_COLOUR[2] = math.max(self.C.CCC_COLOUR[3], self.C.CCC_COLOUR[1])
'''
match_indent = true

# that dark_edition is doing
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "dark_edition = G.C.DARK_EDITION,"
position = "after"
payload = '''
ccc_colour = G.C.CCC_COLOUR,
'''
match_indent = true