[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


# easter egg
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if _c.set == 'Other' then"
position = "before"
payload = '''
if _c.name == 'ccc_Part Of You' then 
            if G.playing_cards then
                for k, v in ipairs(G.playing_cards) do
                    if (v.edition and v.edition.ccc_mirrored) and (G.localization.descriptions.Other.ccc_acts_as_mirror)then 
                        main_end = {}
                        localize{type = 'other', key = 'ccc_acts_as_mirror', nodes = main_end, vars = {}}
                        main_end = main_end[1]
                        break
                    end
                end
            end
end
'''
match_indent = true