[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


# Card:update inject
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == "Cloud 9" then'''
position = "before"
payload = '''
if self.ability.name == "ccc_Secret Shrine" then 
	self.ability.extra.seven_tally = 0
	for k, v in pairs(G.playing_cards) do
		if v:get_id() == 7 then self.ability.extra.seven_tally = self.ability.extra.seven_tally+1 end
	end
end
'''
match_indent = true