[manifest]
version = "1.0.0"
dump_lua = true
priority = 5

## Chameleon tooltip
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if add and not G.GAME.banned_keys[v.key] then'''
position = 'before'
match_indent = true
payload = '''if G.GAME.modifiers.vanilla_only then
    if v.mod then
        add = false
    end 
end
'''

 ## Chameleon tooltip
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if _pool_size == 0 then'''
position = 'before'
match_indent = true
payload = '''if _pool_size == 0 then
    _pool = EMPTY(G.ARGS.TEMP_POOL)
    if G.GAME.modifiers.vanilla_only then
        local replacement_key = pseudorandom_element(new_pool, pseudoseed('vanilla_only'))
        while replacement_key == 'UNAVAILABLE' do
            replacement_key = pseudorandom_element(new_pool, pseudoseed('vanilla_only_resample'))
        end
        if SMODS.ConsumableTypes[_type] and SMODS.ConsumableTypes[_type].default and G.P_CENTERS[SMODS.ConsumableTypes[_type].default] then
            _pool[#_pool+1] = SMODS.ConsumableTypes[_type].default
        elseif _type == 'Tarot' or _type == 'Tarot_Planet' then _pool[#_pool + 1] = "c_strength"
        elseif _type == 'Planet' then _pool[#_pool + 1] = "c_pluto"
        elseif _type == 'Spectral' then _pool[#_pool + 1] = "c_incantation"
        elseif _type == 'Joker' then _pool[#_pool + 1] = "j_joker"
        elseif _type == 'Demo' then _pool[#_pool + 1] = "j_joker"
        elseif _type == 'Voucher' then _pool[#_pool + 1] = "v_blank"
        elseif _type == 'Tag' then _pool[#_pool + 1] = "tag_handy"
        elseif _type == 'Consumeables' then _pool[#_pool + 1] = "c_ceres"
        else _pool[#_pool + 1] = "j_joker"
        end
        _pool_size = 1
    end
end
'''