[manifest]
version = "1.0"
dump_lua = true
priority = 0

# This manifest assumes the following release structure:
#
# DVSimulate/
# ├─ Engine.lua
# ├─ Init.lua
# ├─ Hooks.lua

[[patches]]
[patches.copy]
target = "globals.lua"
position = "append"
sources = [ "Init.lua" ]

[[patches]]
[patches.copy]
target = "functions/common_events.lua"
position = "append"
sources = [ "Engine.lua" ]


[[patches]]
[patches.copy]
target = "functions/common_events.lua"
position = "append"
sources = [ "Hooks.lua" ]
